import React from 'react';
import { useParams } from 'react-router-dom';

export const MockPdfPreview: React.FC = () => {
  const { id } = useParams();

  return (
    <div className="min-h-screen bg-gray-500 flex items-center justify-center p-8">
      <div className="bg-white w-full max-w-4xl min-h-[1056px] shadow-2xl p-12 border border-gray-300">
        <div className="flex justify-between items-start border-b-2 border-black pb-6 mb-8">
          <div>
            <img src="/mm_logo.png" alt="MM Holiday Logo" className="h-16 w-auto mb-2" />
            <p className="text-gray-500 mt-2">123 Travel Road, Bangkok 10110</p>
            <p className="text-gray-500">Tel: 02-123-4567 | Fax: 02-123-4568</p>
          </div>
          <div className="text-right">
            <h2 className="text-3xl font-bold text-blue-800 border-2 border-blue-800 p-2 inline-block">VOUCHER</h2>
            <p className="mt-4 text-lg"><strong>No:</strong> {id === 'uuid-1234' ? 'MM26080001' : 'UNKNOWN'}</p>
            <p><strong>Date:</strong> 2026-08-19</p>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-8 mb-8">
          <div>
            <h3 className="font-bold text-lg mb-2 bg-gray-100 p-2">Guest Details</h3>
            <p><strong>Name:</strong> Mr. John Wick</p>
            <p><strong>Pax:</strong> 2 Adults, 0 Children</p>
          </div>
          <div>
            <h3 className="font-bold text-lg mb-2 bg-gray-100 p-2">Agent/Company</h3>
            <p><strong>Company:</strong> Continental Hotel</p>
            <p><strong>Contact:</strong> +1 234 567 8900</p>
          </div>
        </div>

        <div className="mb-8">
          <h3 className="font-bold text-lg mb-2 bg-blue-100 p-2 text-blue-900">Hotel Accommodation</h3>
          <table className="w-full border-collapse border border-gray-300 text-left">
            <thead>
              <tr className="bg-gray-50">
                <th className="border border-gray-300 p-2">Hotel Name</th>
                <th className="border border-gray-300 p-2">Check In</th>
                <th className="border border-gray-300 p-2">Check Out</th>
                <th className="border border-gray-300 p-2">Room Type</th>
                <th className="border border-gray-300 p-2">Nights</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border border-gray-300 p-2">Grand Hyatt Erawan</td>
                <td className="border border-gray-300 p-2">2026-09-01</td>
                <td className="border border-gray-300 p-2">2026-09-03</td>
                <td className="border border-gray-300 p-2">Deluxe Double</td>
                <td className="border border-gray-300 p-2">2</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="mt-24 flex justify-between px-12">
          <div className="text-center">
            <div className="border-b border-black w-48 mb-2"></div>
            <p>Prepared By</p>
          </div>
          <div className="text-center">
            <div className="border-b border-black w-48 mb-2"></div>
            <p>Authorized Signature</p>
          </div>
        </div>

        <div className="mt-16 text-center text-sm text-gray-400">
          * This is a mock PDF preview rendered in HTML/CSS for demonstration purposes. *<br />
          In production, this endpoint will return a binary application/pdf generated by Puppeteer.
        </div>
      </div>
    </div>
  );
};
